### ISSUE TITLE
Request: support more keywords

### ISSUE THREAD

**Issue by kazerniel** [SimplGy/emoji-magic#7]
it would be handy if the web app offered:

😩 and 😫 when searching for "suffering"

😳 and 😱 when searching for "shocked"

🫣 when searching for "peek", "shy" or "embarrassed"

**Comment by SimplGy** [comment]
Some of these were new unicode, some needed keyword additions. Thanks for the report, resolved via https://github.com/SimplGy/emoji-magic/commit/639badd5135490054d823c0c4a0c9d6c25f0a83d
